import Test.QuickCheck
import Data.List (sort)

-- Consider a "rose tree" - a tree with nodes of type a having zero or more subtrees: 
data Rose a = Node a [Rose a]
  deriving (Eq,Show)

-- Define a zip function
zipRose :: Rose a -> Rose b -> Rose (a,b)

-- So that, for example, zipping the trees A and B gives the Tree C pictured below:

zipRose (Node a tas) (Node b tbs) = Node (a,b) $ zipWith zipRose tas tbs


-- Let us say that a rose tree is "list-shaped" if every node matches either the pattern
-- Node x [t] or Node x [].

-- Define a function 

fromList :: [a] -> Rose a

-- which converts any non-empty list into the corresponding list-shaped tree.   It should be undefined on the empty list. 

fromList [x]    = Node x []
fromList (x:xs) = Node x [fromList xs]

-- using fromList, define prop_zipRose, a property that checks that zipRose does essentially the same thing as zip when its inputs are list-shaped. 

prop_zipRose :: Int -> [Int] -> Bool -> [Bool] -> Bool
prop_zipRose a as b bs = 
   zipRose (fromList as') (fromList bs') == fromList (zip as' bs')
      where as' = a:as
            bs' = b:bs  
       
-- Note: you need some kind of type signature otherwise it will test at type ()
-- OK to have just two arguments and use: not (null as) && not (null bs) ==> ...


-- Write the code necessary to make Rose a useful instance of class Functor.  
instance Functor Rose where 
    fmap f (Node x ts) = Node (f x) (map (fmap f) ts)

------------------
{-
In this question you are to define a version of the standard QuickCheck function listOf in two ways. In both definitions you may not use vectorOf, and you may not use any functions not explicitly listed in the given list of functions except for arbitrary :: Gen Int. 

1. with the help of recursion
2. without recursion, using the given standard functions (except for vectorOf)
-}

listOf1, listOf2 :: Gen a -> Gen [a]
listOf1 g = do
     len <- arbitrary :: Gen Int
     go (abs len)

    where go 0 = return []
          go n = do 
                a <- g
                as <- go (n-1)
                return (a:as)

listOf2 g = do
     len <- arbitrary
     sequence $ replicate (abs len) g

{- Define a function listContaining :: Gen a -> a -> Gen [a]  such that g `ListContaining` x generates lists of elements of the same type as x, such that (i) the list is guaranteed to contain at least one copy of x, and (ii) all other elements are generated by g (which may or may not generate other copies of x). -}

listContaining :: Gen a -> a -> Gen [a]
listContaining g a = do 
    front <- listOf g
    back <- listOf g
    return (front ++ [a] ++ back)

----------------------------------------------------------------
{- 
A certain workplace is on several floors.  Each floor is separated by a certain number of steps.

Here is an example: 
-}

type Steps = Int -- non-negative
type Floor = Int -- non-negative
type Workplace = [Steps] -- non-empty

example :: Workplace
example = [30,20,20,20,40]

{-
This example workplace represents a building with 6 floors, numbered 0 to 5. The number of steps between floor 0 (ground floor) and floor 1 is 30, whereas the number between floor 1 and 2 is 20, etc.

The activity of an employee can be modelled as a list of the floors they visit in a working day.

-}

type Activity = [Floor]

-- For example, [2,1,5,0] represents the movements of Dave, who wakes up in his office on floor 2, visits the canteen on floor 1, the coffee room on floor 5, then leaves on floor 0. 

-- Define a function 

stepCount :: Workplace -> Activity -> Steps

-- which computes the total number of steps in a given day's activity. 
stepCount stairs acts = 
    let moves = zip acts (drop 1 acts)
        moveLength (start,end) = sum . take upper . drop lower $ stairs
                                 where [lower,upper] = sort [start,end]
    in sum $ map moveLength moves        

{-
The workplace want to install a lift (elevator).  Unfortunately they can only afford a lift that goes between two consecutive floors.  To decide which floor the lift should be installed on (we say that the lift is on floor n if it goes between floors n and n+1) they take the data from the last year (a list of the activities of all employees), and choose to install the lift on the floor that will minimise the number of steps that are taken - assuming that everyone will always take the lift when possible!

Define a function
-}

bestPlace :: Workplace -> [Activity] -> Floor

-- which calculates the best place for the list.  If there are several best choices then you may return any one of them. 

-- total steps for a given collection of activities
totalSteps :: Workplace -> [Activity] -> Steps
totalSteps stairs = sum . map (stepCount stairs)

-- effect of installing a lift at a given floor (assumes that the floor is valid) is to set the number of steps to zero.
installLift :: Floor -> Workplace -> Workplace
installLift floor stairs = below ++ [0] ++ above
       where (below,_:above) = splitAt floor stairs 

bestPlace stairs activity = snd $ minimum allOutcomes
  where
    choices             = [0..length stairs - 1] -- possible floors
    installEffect       :: Floor -> Steps
    installEffect floor = totalSteps (installLift floor stairs) activity 
    allOutcomes         :: [(Steps,Floor)]
    allOutcomes         = [(installEffect floor, floor) | floor <- choices]

-- You may assume that the floor numbers are always valid for the given staircase, and that the staircase is non empty and has at least two floors. Hint: the effect of putting the lift on floor n can be calculated by changing the nth element in the staircase to 0. 

-- Hint: for maximal points, try to break the problem into understandable parts, and use type signatures to clarify what the parts do. 


